# Generated by Django 4.0.3 on 2023-03-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, null=True)),
                ('image', models.CharField(max_length=150, null=True)),
                ('amount', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assocname', models.CharField(max_length=150, null=True)),
                ('award', models.CharField(max_length=150, null=True)),
                ('pname', models.CharField(max_length=150, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
                ('date', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.CharField(max_length=150, null=True)),
                ('fromdate', models.CharField(max_length=150, null=True)),
                ('todate', models.CharField(max_length=150, null=True)),
                ('days', models.CharField(max_length=150, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('tamount', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('addr', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(max_length=150, null=True)),
                ('district', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Giftgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, null=True)),
                ('image', models.CharField(max_length=150, null=True)),
                ('amount', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('password', models.TextField(max_length=50, null=True)),
                ('types', models.CharField(max_length=100, null=True)),
                ('status', models.TextField(default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assocname', models.CharField(max_length=150, null=True)),
                ('event', models.CharField(max_length=150, null=True)),
                ('date', models.CharField(max_length=150, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
                ('loc', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=150, null=True)),
                ('custid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('addr', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(max_length=150, null=True)),
                ('district', models.CharField(max_length=150, null=True)),
                ('specialization', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('image', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=150, null=True)),
                ('association1', models.CharField(max_length=150, null=True)),
                ('logid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Workstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=150, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
                ('date', models.CharField(max_length=150, null=True)),
                ('bkid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.booking')),
                ('phid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=150, null=True)),
                ('cmodel', models.CharField(max_length=150, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
                ('image', models.CharField(max_length=150, null=True)),
                ('phid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('feedback', models.CharField(max_length=150, null=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.customer')),
                ('phid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.artgallery')),
                ('phid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer')),
                ('pmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.payment')),
                ('saleid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.giftgallery')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=150, null=True)),
                ('did', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Photographervideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=150, null=True)),
                ('phid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='Photographerimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, null=True)),
                ('image', models.CharField(max_length=150, null=True)),
                ('phid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='phid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer'),
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=150, null=True)),
                ('amount', models.CharField(max_length=150, null=True)),
                ('phid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer')),
            ],
        ),
        migrations.AddField(
            model_name='giftgallery',
            name='phid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=150, null=True)),
                ('rating', models.CharField(max_length=150, null=True)),
                ('phid', models.CharField(max_length=150, null=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='logid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.login'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150, null=True)),
                ('cdesc', models.CharField(max_length=150, null=True)),
                ('date', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(max_length=150, null=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pkgid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.packages'),
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('addr', models.CharField(max_length=150, null=True)),
                ('assochead', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('phno', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(default='0', max_length=150, null=True)),
                ('logid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='artgallery',
            name='phid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer'),
        ),
    ]
