# Generated by Django 4.2 on 2023-05-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='fb',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='insta',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='profile',
            field=models.ImageField(null=True, upload_to='Profile'),
        ),
        migrations.CreateModel(
            name='ForAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, null=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.customer')),
                ('phid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapapp.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='album')),
                ('fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapapp.foralbum')),
            ],
        ),
    ]
